### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Aimannnhakim** [xinyooo/deepfake-detection#5]
![tanya](https://user-images.githubusercontent.com/47772440/81626778-4201a800-942f-11ea-95ea-127b0b023abf.PNG)

heloo, about the metadata in the training sample videos file,
the **highlighted video name**, should be the deepfake videos, 
and the **circled video name**, should be the corresponding original one right?
am i right?

im confused because the the circled video name, does not exist in the sample video file

thank you in advance

**Comment by xinyooo** [comment]
Yes u r right.
