### ISSUE TITLE
Unable to output img

### ISSUE THREAD

**Issue by Carson9999** [xinyooo/deepfake-detection#6]
Hi, I have cloned your code for capture_img.ipynb and I don't see any image file outputed by the program, can you help me, thank you so much.

**Comment by xinyooo** [comment]
Please check the permission of your user account and environment.

**Comment by Aimannnhakim** [comment]
> Hi, I have cloned your code for capture_img.ipynb and I don't see any image file outputed by the program, can you help me, thank you so much.

u should create the directory for the output file first , and make sure the address of the directory is correctly set
